posts/urls.py
from django.urls import path
from . import views

app_name = 'posts_list'
urlpatterns = [
    path('', views.index, name='posts_list'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts_list'),
]

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts_list')),
    path('admin/', admin.site.urls)
]

posts/models.py
from turtle import title
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
        return self.title
        
class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    group = models.ForeignKey(
        Group,
        related_name="group",
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )


# Create your models here.

posts/views.py
from multiprocessing import context
from django.http import HttpResponse
# Create your views here.
from .models import Post, Group
from django.shortcuts import render, get_object_or_404

def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    template = 'posts/index.html'
    return render(request, template, context)

def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context) 

templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load static %}
    <link rel='stylesheet' href='{% static 'css/bootstrap.min.css' %}'>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>       
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

templates/includes/footer.html
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p> 

templates/includes/header.html
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="index.html">
          <a href='{% url 'posts_list:posts_list' %}'>
            {% load static %}
            <img src="{% static 'img/logo.png' %}">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
          </a>
        </a>
      </div>
    </nav>      

templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
Записи сообщества {{ group }}.
{% endblock %}
{% block content %}
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
<a href="">все записи группы</a>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}

templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
    Последние обновления на сайте
{% endblock %}
{% block content %}
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
<a href="">все записи группы</a>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}